"""SANTA TEST."""
from santa import NiceAndNaughtyList, Wishlist, ProductionAndStock


def test_nice_and_naughty_list():
    """Test the class NiceAndNaughtyList from santa.py."""
    nanl = NiceAndNaughtyList("ex15_nice_list.csv", "ex15_naughty_list.csv")

    nil = [('Libby', 'United Kingdom'),
           ('Keira', 'Germany'),
           ('Lexie', 'Canada'),
           ('Amelia', 'South Africa'),
           ('Evelyn', 'Puerto Rico'),
           ('Carissa', 'United Kingdom'),
           ('Marisol', 'Estonia'),
           ('Dylan', 'Peru'),
           ('Ben', 'Australia'),
           ('Cain', 'Australia'),
           ('Darius', 'Australia'),
           ('Edward', 'Puerto Rico'),
           ('Freddie', 'South Africa'),
           ('Jenson', 'Estonia'),
           ('Armando', 'United Kingdom'),
           ('Jakob', 'Sweden'),
           ('Alvin', 'Canada'),
           ('Peter', 'Peru'),
           ('Louis', 'Sweden'),
           ('Spencer', 'Sweden'),
           ('Mason', 'Canada'),
           ('Rhys', 'Estonia'),
           ('Reid', 'Peru'),
           ('Caden', 'United States of America'),
           ('Quinn', 'Germany'),
           ('Lesley', 'Peru'),
           ('Kai', 'Estonia'),
           ('Jess', 'United States of America'),
           ('Jaden', 'Germany'),
           ('Ash', 'Sweden'),
           ('Skyler', 'Peru'),
           ('Jordan', 'South Africa'),
           ('Aubrey', 'Puerto Rico'),
           ('Alexis', 'South Africa'),
           ('Eleanor', 'Puerto Rico'),
           ('Scarlett', 'Australia'),
           ('Rachael', 'Sweden'),
           ('Lorelei', 'Sweden'),
           ('Phoebe', 'Puerto Rico'),
           ('Ariel', 'United Kingdom'),
           ('Kimberly', 'Sweden'),
           ('Chloe', 'Puerto Rico'),
           ('Sofie', 'Australia'),
           ('Jodie', 'Sweden'),
           ('Hollie', 'Canada'),
           ('Baylee', 'South Africa'),
           ('Brennan', 'Puerto Rico'),
           ('Harper', 'South Africa'),
           ('Lance', 'South Africa'),
           ('Scott', 'Sweden'),
           ('Ollie', 'United Kingdom'),
           ('Marc', 'Peru'),
           ('Otto', 'United States of America'),
           ('Mark', 'Puerto Rico'),
           ('Denzel', 'Canada'),
           ('Toby', 'Germany'),
           ('Tobias', 'Peru'),
           ('Elliot', 'United Kingdom'),
           ('Ellis', 'Sweden'),
           ('Sean', 'Sweden'),
           ('Dominik', 'United Kingdom'),
           ('Gunnar', 'South Africa'),
           ('Darryl', 'Australia'),
           ('Josh', 'Puerto Rico'),
           ('Jackson', 'South Africa'),
           ('Dayton', 'Estonia'),
           ('Evan', 'Puerto Rico'),
           ('Levi', 'Puerto Rico'),
           ('Harvey', 'South Africa'),
           ('Ewan', 'Estonia'),
           ('Drew', 'Germany'),
           ('Rylan', 'Peru'),
           ('Shane', 'Peru'),
           ('Josiah', 'Sweden'),
           ('Max', 'Peru'),
           ('Dillion', 'Germany'),
           ('Albert', 'Canada'),
           ('Nathan', 'Estonia'),
           ('Nathaniel', 'Australia'),
           ('Joaquin', 'Puerto Rico'),
           ('Declan', 'Estonia'),
           ('Benton', 'Puerto Rico'),
           ('Stan', 'Puerto Rico'),
           ('Steve', 'Sweden'),
           ('Lewis', 'Peru'),
           ('Javier', 'South Africa'),
           ('Roy', 'Canada'),
           ('Nicholas', 'Germany'),
           ('Simeon', 'South Africa'),
           ('Milo', 'Puerto Rico'),
           ('Calvin', 'Australia'),
           ('James', 'Puerto Rico'),
           ('Jon', 'Canada'),
           ('Ernest', 'United States of America'),
           ('Patrick', 'Estonia'),
           ('Logan', 'Canada'),
           ('Atticus', 'Estonia'),
           ('Luke', 'Australia'),
           ('Rodney', 'Canada'),
           ('Lucas', 'Canada'),
           ('Vaughn', 'United Kingdom'),
           ('Marcel', 'Peru'),
           ('Victor', 'Sweden'),
           ('Noah', 'Sweden'),
           ('Jimmy', 'Germany'),
           ('Gail', 'Peru'),
           ('Frankie', 'United States of America'),
           ('Bella', 'Sweden'),
           ('Polly', 'Sweden'),
           ('Nora', 'Peru'),
           ('Lacey', 'Estonia'),
           ('Georgina', 'Puerto Rico'),
           ('Addison', 'United States of America'),
           ('Natalie', 'Puerto Rico'),
           ('Adeline', 'Australia'),
           ('Ariana', 'Estonia'),
           ('Astrid', 'South Africa'),
           ('Charlotte', 'Germany'),
           ('Paisley', 'Estonia'),
           ('Brooklyn', 'Peru'),
           ('Angel', 'Canada'),
           ('Gabbie', 'Canada'),
           ('Angelika', 'Sweden'),
           ('Nadia', 'Estonia'),
           ('Hazel', 'Germany'),
           ('Francesca', 'Peru'),
           ('Arya', 'Peru'),
           ('Caitlin', 'United States of America'),
           ('Myra', 'Australia'),
           ('Eden', 'United Kingdom'),
           ('Dolly', 'South Africa'),
           ('Eliza', 'United Kingdom'),
           ('Josie', 'South Africa'),
           ('Ivy', 'Sweden'),
           ('Georgia', 'Germany'),
           ('Ariella', 'Canada'),
           ('Arianna', 'United States of America'),
           ('Meredith', 'Canada'),
           ('Abigail', 'Australia'),
           ('Miriam', 'United States of America'),
           ('Holly', 'United States of America'),
           ('Annie', 'Peru'),
           ('Matteo', 'Estonia'),
           ('Olly', 'United States of America'),
           ('Kian', 'Sweden'),
           ('Zack', 'Sweden'),
           ('Arlo', 'Peru'),
           ('Archer', 'Puerto Rico'),
           ('Parker', 'United Kingdom'),
           ('Fabian', 'Puerto Rico'),
           ('Montgomery', 'Australia'),
           ('Kevin', 'South Africa'),
           ('Jesse', 'Estonia'),
           ('Tate', 'Peru'),
           ('Luis', 'Australia'),
           ('Travis', 'Canada'),
           ('Carl', 'Australia'),
           ('Fletcher', 'Australia'),
           ('Eddie', 'United Kingdom'),
           ('Lenno', 'Australia'),
           ('Sidney', 'South Africa'),
           ('Dennis', 'Germany'),
           ('Jensen', 'Canada'),
           ('Sam', 'United Kingdom'),
           ('Oscar', 'United Kingdom'),
           ('Perry', 'Peru'),
           ('Ted', 'Canada'),
           ('Ralph', 'Puerto Rico'),
           ('Fraser', 'United States of America'),
           ('Neil', 'Peru'),
           ('Herman', 'Germany'),
           ('Russell', 'Sweden'),
           ('Wayne', 'United Kingdom'),
           ('Wyatt', 'Australia'),
           ('Hector', 'Peru'),
           ('Miles', 'Canada'),
           ('Zach', 'Estonia'),
           ('Damian', 'South Africa'),
           ('Isaac', 'United Kingdom'),
           ('Tristan', 'Canada'),
           ('Hans', 'Germany'),
           ('Curtis', 'United States of America'),
           ('Hugo', 'Germany'),
           ('Casey', 'United States of America'),
           ('Kylie', 'Canada'),
           ('Nicole', 'United States of America'),
           ('Ada', 'Estonia'),
           ('Adele', 'Puerto Rico'),
           ('Agnes', 'Sweden'),
           ('ALbert', 'Sweden'),
           ('Allen', 'Canada'),
           ('Mario', 'Australia'),
           ('Brian', 'Sweden'),
           ('Tiffany', 'Canada'),
           ('Veronica', 'South Africa'),
           ('Jodi', 'Australia'),
           ('Vivian', 'Sweden'),
           ('Sara', 'United Kingdom'),
           ('Connie', 'Canada'),
           ('Ella', 'South Africa'),
           ('Leo', 'South Africa'),
           ('Philip', 'Puerto Rico'),
           ('Craig', 'United States of America'),
           ('Brendan', 'Peru'),
           ('Jeff', 'Estonia'),
           ('Shaun', 'United States of America'),
           ('Orville', 'United Kingdom'),
           ('Kent', 'Australia'),
           ('Derek', 'Australia'),
           ('Donald', 'United Kingdom'),
           ('Earl', 'South Africa'),
           ('Leon', 'Peru'),
           ('Roger', 'Australia'),
           ('Seth', 'Estonia'),
           ('Stella', 'United States of America'),
           ('Loretta', 'United Kingdom'),
           ('Laura', 'United States of America'),
           ('Michelle', 'United States of America'),
           ('Gina', 'Canada'),
           ('Selena', 'Australia'),
           ('Alice', 'Sweden'),
           ('Beverly', 'Australia'),
           ('Dolores', 'Puerto Rico'),
           ('Stefanie', 'Sweden'),
           ('Yvonne', 'Puerto Rico'),
           ('Irma', 'Germany'),
           ('Mariah', 'Canada'),
           ('Maureen', 'United States of America'),
           ('Denise', 'Canada'),
           ('Howard', 'South Africa'),
           ('Karl', 'Puerto Rico'),
           ('Martin', 'Canada'),
           ('Sebastian', 'Puerto Rico'),
           ('Kilian', 'Canada'),
           ('Eugene', 'Sweden'),
           ('Estelle', 'Germany'),
           ('Arnold', 'Sweden'),
           ('Arthur', 'Canada'),
           ('Gerald', 'Sweden'),
           ('Margarita', 'Estonia'),
           ('Franz', 'South Africa'),
           ('Marcus', 'United Kingdom'),
           ('Marvin', 'United Kingdom'),
           ('Mathias', 'Australia'),
           ('Niko', 'Australia'),
           ('Naomi', 'Estonia'),
           ('Paula', 'South Africa'),
           ('Raphael', 'United Kingdom'),
           ('Rupert', 'Germany'),
           ('Sabrina', 'United States of America'),
           ('Ruth', 'Estonia'),
           ('Sven', 'Canada'),
           ('Tim', 'Peru'),
           ('Timothy', 'Estonia'),
           ('Gilbert', 'South Africa'),
           ('Gustav', 'Sweden'),
           ('Klaus', 'Canada'),
           ('Lars', 'Canada'),
           ('Dirk', 'Germany'),
           ('Emilia', 'United Kingdom'),
           ('Emma', 'Puerto Rico'),
           ('Eva', 'South Africa'),
           ('Gwen', 'United Kingdom'),
           ('Ramona', 'Germany'),
           ('Casper', 'Puerto Rico'),
           ('Kayleigh', 'United States of America'),
           ('Fern', 'Canada'),
           ('Daisy', 'Canada'),
           ('Maria', 'Canada'),
           ('Mimi', 'Canada'),
           ('Tessa', 'Puerto Rico'),
           ('Esther', 'Sweden'),
           ('Martha', 'United Kingdom'),
           ('Jasmin', 'Estonia'),
           ('Ida', 'United States of America'),
           ('Leonie', 'Peru'),
           ('Zoe', 'Estonia'),
           ('Courtney', 'United States of America'),
           ('Matilda', 'Estonia'),
           ('Stephanie', 'United Kingdom'),
           ('Dale', 'Germany'),
           ('Elle', 'Australia'),
           ('Leia', 'Estonia'),
           ('Carley', 'Sweden'),
           ('Sophie', 'South Africa'),
           ('Gabrielle', 'Sweden'),
           ('Alexa', 'Peru'),
           ('Mariam', 'Canada'),
           ('Catherine', 'South Africa'),
           ('Anya', 'United Kingdom'),
           ('Stacy', 'United Kingdom')]
    assert nanl.nice_list == nil

    nal = [('Tanya', 'United Kingdom'),
           ('Jamie', 'Canada'),
           ('Chelsea', 'South Africa'),
           ('Taylor', 'United Kingdom'),
           ('Hannah', 'United States of America'),
           ('Megan', 'Germany'),
           ('Georgie', 'Estonia'),
           ('Christine', 'South Africa'),
           ('Ashley', 'South Africa'),
           ('Kelly', 'Puerto Rico'),
           ('Sylvia', 'United Kingdom'),
           ('Rose', 'Puerto Rico'),
           ('Helen', 'Australia'),
           ('Edie', 'Canada'),
           ('Alexandra', 'United Kingdom'),
           ('Sandra', 'Germany'),
           ('Heidi', 'Peru'),
           ('India', 'Canada'),
           ('Lara', 'Germany'),
           ('Joel', 'Sweden'),
           ('David', 'Sweden'),
           ('Rachel', 'Peru'),
           ('Daniel', 'Puerto Rico'),
           ('Jonathan', 'Sweden'),
           ('Annabel', 'United Kingdom'),
           ('Leila', 'Puerto Rico'),
           ('Elizabeth', 'United States of America'),
           ('Gemma', 'Canada'),
           ('Elena', 'Puerto Rico'),
           ('Mollie', 'Germany'),
           ('Charlie', 'South Africa'),
           ('Danielle', 'South Africa'),
           ('Meghan', 'United States of America'),
           ('Tyler', 'Peru'),
           ('Betty', 'Germany'),
           ('Elsie', 'Canada'),
           ('Lucy', 'United States of America'),
           ('April', 'Puerto Rico'),
           ('Maggie', 'Germany'),
           ('Anne', 'Australia'),
           ('Nancy', 'Puerto Rico'),
           ('Julie', 'Estonia'),
           ('Kyla', 'Peru'),
           ('Sharon', 'Estonia'),
           ('Harriet', 'Puerto Rico'),
           ('Isabel', 'Estonia'),
           ('Christian', 'South Africa'),
           ('Maxwell', 'Puerto Rico'),
           ('Connor', 'United Kingdom'),
           ('Harley', 'Germany'),
           ('Alan', 'Puerto Rico'),
           ('Erik', 'Australia'),
           ('Charles', 'United Kingdom'),
           ('Robbie', 'Peru'),
           ('Robin', 'South Africa'),
           ('Jeremy', 'Sweden'),
           ('Omar', 'Germany'),
           ('Oliver', 'United Kingdom'),
           ('Julia', 'Australia'),
           ('Kyle', 'Estonia'),
           ('Jenna', 'Sweden'),
           ('Cory', 'Puerto Rico'),
           ('Ricky', 'Germany'),
           ('Douglas', 'Australia'),
           ('Clyde', 'Australia'),
           ('Juan', 'United States of America'),
           ('Callum', 'Peru'),
           ('Anita', 'South Africa'),
           ('Adrian', 'Puerto Rico'),
           ('Austin', 'Peru'),
           ('Justin', 'Peru'),
           ('Edgar', 'Canada'),
           ('Renee', 'South Africa'),
           ('Felix', 'Estonia'),
           ('Marshall', 'Sweden'),
           ('Lily', 'Peru'),
           ('Archie', 'United Kingdom'),
           ('Annika', 'Estonia'),
           ('Aiden', 'Canada'),
           ('Greg', 'Puerto Rico'),
           ('Laurence', 'Sweden'),
           ('Brett', 'Puerto Rico'),
           ('Gregory', 'Canada'),
           ('Vince', 'Peru'),
           ('William', 'Peru'),
           ('Liam', 'United States of America'),
           ('Matthew', 'Germany'),
           ('Billy', 'United Kingdom'),
           ('Adam', 'Peru'),
           ('Michael', 'Estonia'),
           ('Ronald', 'South Africa'),
           ('Harry', 'United States of America'),
           ('Henry', 'Canada'),
           ('Stefan', 'Sweden'),
           ('Thomas', 'South Africa'),
           ('Alistair', 'Canada'),
           ('Ian', 'Peru'),
           ('Jay', 'United Kingdom'),
           ('Theodore', 'United Kingdom'),
           ('Jasper', 'Puerto Rico'),
           ('Riley', 'South Africa'),
           ('Gene', 'Australia'),
           ('Eli', 'Puerto Rico'),
           ('Mel', 'Sweden'),
           ('Danni', 'United States of America'),
           ('Nicky', 'South Africa'),
           ('Morgan', 'United States of America'),
           ('Bailey', 'Peru')]
    assert nanl.naughty_list == nal

    assert nanl.get_nice_list() == nil
    assert nanl.get_naughty_list() == nal


def test_wishlist():
    """Test the class Wishlist from santa.py."""
    wishl = Wishlist("ex15_wish_list.csv")

    actual_wishes = [('Libby', ['Zebra Jumpy', 'Princess dress', 'Lego death star']),
                     ('Keira', ['LED light up sneakers', '7200 Riot Points gift card']), ('Lexie', ['Mermaid barbie',
                                                                                                    'Pink fluffy pen',
                                                                                                    'World of Warcraft: Shadowlands Collectors Edition']),
                     ('Amelia', ['Wall-mount diamond pickaxe', 'Magic: The Gathering Commander Legends booster box']),
                     ('Evelyn', ['Wall-mount diamond pickaxe', '7200 Riot Points gift card', 'Avocado']),
                     ('Carissa', ['Baby Yoda plushie', 'Nintendo Switch', 'Football shoes']),
                     ('Marisol', ['Magic: The Gathering Commander Legends booster box']),
                     ('Dylan', ['Roller skates', 'Cyberpunk 2077']), ('Ben', ['Polar bear plushie']),
                     ('Cain', ['VHS player', "Harry Potter and the Philosopher's Stone"]), ('Darius', ['Baby born doll',
                                                                                                       'Magic: The Gathering Commander Legends booster box',
                                                                                                       'Horse riding helmet']),
                     ('Edward', ['Trick scooter', 'Baby born doll', 'Tablet computer']),
                     ('Freddie', ['Color pencil set', 'Toy train set', 'Brunette Barbie doll']),
                     ('Jenson', ['Toy train set', 'Jaipur board game', 'Acrylic paint brush set']),
                     ('Armando', ['Nerf rifle', 'Remote controlled car']),
                     ('Jakob', ['Frozen Elsa electric toothbrush', 'Raspberry Pi 4']), ('Alvin', ['Swimming flippers']),
                     ('Peter', ['LED light up sneakers']), ('Louis', ['Football shoes', 'Tablet computer']),
                     ('Spencer', ['Remote controlled car', 'Fortnite t-shirt', 'Raspberry Pi 4']),
                     ('Mason', ['Toy truck', 'Beyblade Burst spinner']), ('Rhys', ['Crayons']),
                     ('Reid', ['Book about dinosaurs', 'Color pencil set', 'Skateboard']),
                     ('Caden', ['New phone', 'Baby born doll', 'Car carpet']), ('Quinn', ['Small watering can']),
                     ('Lesley', ['Briefcase of art supplies']), ('Kai', ['Small watering can']),
                     ('Jess', ['Carbon fiber road bike']),
                     ('Jaden', ['Dungeons and Dragons 5th Edition Starter Set', 'New phone', 'Ninja Turtles backpack']),
                     ('Ash', ['Briefcase of art supplies']), ('Skyler', ['New phone', 'New phone']),
                     ('Jordan', ['Magic: The Gathering Commander Legends booster box']),
                     ('Aubrey', ['Toy dinosaur play set']), ('Alexis', ['Running shoes']),
                     ('Eleanor', ['Spiderman costume', 'Polyhedral dice set']),
                     ('Scarlett', ['Running shoes', 'Piggy bank', 'Ballet shoes']),
                     ('Rachael', ['Clear Night Sky puzzle', 'Xbox Series X', 'Doll stroller']),
                     ('Lorelei', ['Raspberry Pi 4', 'Digital camera']),
                     ('Phoebe', ['Clear Night Sky puzzle', 'Toy train set']),
                     ('Ariel', ['Basketball', 'Baby brother', 'LOL Dolls surprise egg']),
                     ('Kimberly', ['Raspberry Pi 4', 'Wireless headphones']), ('Chloe', ['Wireless headphones']),
                     ('Sofie', ['Ninja Turtles backpack']),
                     ('Jodie', ['LED light up sneakers', 'Small watering can', '7200 Riot Points gift card']),
                     ('Hollie', ['Acrylic paint brush set', 'Football shoes', 'Xbox Series X']),
                     ('Baylee', ['Carbon fiber road bike']), ('Brennan', ['Pink tricycle']),
                     ('Harper', ['Jaipur board game', 'Princess dress', 'Toy kitchen set']),
                     ('Lance', ['Indoor bowling set']), ('Scott', ['Polyhedral dice set'])]

    assert list(wishl.wishes.items()) == actual_wishes
    assert list(wishl.get_wishes().items()) == actual_wishes


def test_production_and_stock():
    """Test the class ProductionAndStock from santa.py."""
    nanl = NiceAndNaughtyList(r"ex15_nice_list.csv", r"ex15_naughty_list.csv")
    wishl = Wishlist(r"ex15_wish_list.csv")
    pas = ProductionAndStock("https://cs.ttu.ee/services/xmas/gift?name=", nanl, wishl)

    assert pas.get_product_list() == {}
    assert pas.get_recipient_list() == {}

    pas.parse_wishlist_into_products_and_recipients()

    product_list = {
        '7200 Riot Points gift card': {'Count': 3,
                                       'material_cost': '50',
                                       'production_time': '0.1',
                                       'weight_in_grams': '10'},
        'Acrylic paint brush set': {'Count': 2,
                                    'material_cost': '13.59',
                                    'production_time': '3.4',
                                    'weight_in_grams': '200'},
        'Avocado': {'material_cost': '2',
                    'production_time': '60',
                    'weight_in_grams': '68'},
        'Baby Yoda plushie': {'material_cost': '29',
                              'production_time': '3',
                              'weight_in_grams': '200'},
        'Baby born doll': {'Count': 3,
                           'material_cost': '25',
                           'production_time': '3',
                           'weight_in_grams': '900'},
        'Baby brother': {'material_cost': '4000',
                         'production_time': '6480',
                         'weight_in_grams': '3425'},
        'Ballet shoes': {'material_cost': '39',
                         'production_time': '2',
                         'weight_in_grams': '150'},
        'Basketball': {'material_cost': '30',
                       'production_time': '3',
                       'weight_in_grams': '900'},
        'Beyblade Burst spinner': {'material_cost': '29.99',
                                   'production_time': '3',
                                   'weight_in_grams': '300'},
        'Book about dinosaurs': {'material_cost': '5',
                                 'production_time': '8',
                                 'weight_in_grams': '250'},
        'Briefcase of art supplies': {'Count': 2,
                                      'material_cost': '35',
                                      'production_time': '4',
                                      'weight_in_grams': '3200'},
        'Brunette Barbie doll': {'material_cost': '25',
                                 'production_time': '5',
                                 'weight_in_grams': '50'},
        'Car carpet': {'material_cost': '99',
                       'production_time': '7',
                       'weight_in_grams': '1500'},
        'Carbon fiber road bike': {'Count': 2,
                                   'material_cost': '5499',
                                   'production_time': '100',
                                   'weight_in_grams': '6900'},
        'Clear Night Sky puzzle': {'Count': 2,
                                   'material_cost': '45',
                                   'production_time': '50',
                                   'weight_in_grams': '1500'},
        'Color pencil set': {'Count': 2,
                             'material_cost': '6',
                             'production_time': '1',
                             'weight_in_grams': '100'},
        'Crayons': {'material_cost': '5',
                    'production_time': '1',
                    'weight_in_grams': '50'},
        'Cyberpunk 2077': {'material_cost': '59',
                           'production_time': '0.5',
                           'weight_in_grams': '30'},
        'Digital camera': {'material_cost': '39',
                           'production_time': '18',
                           'weight_in_grams': '870'},
        'Doll stroller': {'material_cost': '56',
                          'production_time': '15',
                          'weight_in_grams': '2100'},
        'Dungeons and Dragons 5th Edition Starter Set': {'material_cost': '19.99',
                                                         'production_time': '3',
                                                         'weight_in_grams': '1000'},
        'Football shoes': {'Count': 3,
                           'material_cost': '59',
                           'production_time': '7',
                           'weight_in_grams': '690'},
        'Fortnite t-shirt': {'material_cost': '5',
                             'production_time': '1',
                             'weight_in_grams': '100'},
        'Frozen Elsa electric toothbrush': {'material_cost': '59',
                                            'production_time': '4',
                                            'weight_in_grams': '450'},
        "Harry Potter and the Philosopher's Stone": {'material_cost': '7.99',
                                                     'production_time': '15',
                                                     'weight_in_grams': '300'},
        'Horse riding helmet': {'material_cost': '89',
                                'production_time': '5',
                                'weight_in_grams': '2500'},
        'Indoor bowling set': {'material_cost': '69',
                               'production_time': '6',
                               'weight_in_grams': '3500'},
        'Jaipur board game': {'Count': 2,
                              'material_cost': '15',
                              'production_time': '3',
                              'weight_in_grams': '500'},
        'LED light up sneakers': {'Count': 3,
                                  'material_cost': '35',
                                  'production_time': '5.89',
                                  'weight_in_grams': '250'},
        'LOL Dolls surprise egg': {'material_cost': '15',
                                   'production_time': '1',
                                   'weight_in_grams': '100'},
        'Lego death star': {'material_cost': '599',
                            'production_time': '30',
                            'weight_in_grams': '2000'},
        'Magic': {'Count': 4,
                  'material_cost': '189',
                  'production_time': '15',
                  'weight_in_grams': '900'},
        'Mermaid barbie': {'material_cost': '25',
                           'production_time': '5',
                           'weight_in_grams': '50'},
        'Nerf rifle': {'material_cost': '30',
                       'production_time': '10',
                       'weight_in_grams': '300'},
        'New phone': {'Count': 3,
                      'material_cost': '100',
                      'production_time': '9',
                      'weight_in_grams': '200'},
        'Ninja Turtles backpack': {'Count': 2,
                                   'material_cost': '25',
                                   'production_time': '3',
                                   'weight_in_grams': '350'},
        'Nintendo Switch': {'material_cost': '359',
                            'production_time': '19',
                            'weight_in_grams': '200'},
        'Piggy bank': {'material_cost': '13',
                       'production_time': '4',
                       'weight_in_grams': '300'},
        'Pink fluffy pen': {'material_cost': '3',
                            'production_time': '1',
                            'weight_in_grams': '60'},
        'Pink tricycle': {'material_cost': '159',
                          'production_time': '8',
                          'weight_in_grams': '5400'},
        'Polar bear plushie': {'material_cost': '15',
                               'production_time': '2',
                               'weight_in_grams': '200'},
        'Polyhedral dice set': {'Count': 2,
                                'material_cost': '13',
                                'production_time': '3',
                                'weight_in_grams': '10'},
        'Princess dress': {'Count': 2,
                           'material_cost': '17',
                           'production_time': '5',
                           'weight_in_grams': '278'},
        'Raspberry Pi 4': {'Count': 4,
                           'material_cost': '57',
                           'production_time': '10',
                           'weight_in_grams': '100'},
        'Remote controlled car': {'Count': 2,
                                  'material_cost': '37',
                                  'production_time': '13',
                                  'weight_in_grams': '2100'},
        'Roller skates': {'material_cost': '64',
                          'production_time': '12',
                          'weight_in_grams': '1670'},
        'Running shoes': {'Count': 2,
                          'material_cost': '39',
                          'production_time': '6',
                          'weight_in_grams': '590'},
        'Skateboard': {'material_cost': '67',
                       'production_time': '9',
                       'weight_in_grams': '1350'},
        'Small watering can': {'Count': 3,
                               'material_cost': '7',
                               'production_time': '2',
                               'weight_in_grams': '540'},
        'Spiderman costume': {'material_cost': '17',
                              'production_time': '4',
                              'weight_in_grams': '278'},
        'Swimming flippers': {'material_cost': '25',
                              'production_time': '3',
                              'weight_in_grams': '1000'},
        'Tablet computer': {'Count': 2,
                            'material_cost': '259',
                            'production_time': '19',
                            'weight_in_grams': '430'},
        'Toy dinosaur play set': {'material_cost': '15',
                                  'production_time': '2',
                                  'weight_in_grams': '150'},
        'Toy kitchen set': {'material_cost': '89',
                            'production_time': '10',
                            'weight_in_grams': '2499'},
        'Toy train set': {'Count': 3,
                          'material_cost': '49',
                          'production_time': '6',
                          'weight_in_grams': '890'},
        'Toy truck': {'material_cost': '13',
                      'production_time': '4',
                      'weight_in_grams': '300'},
        'Trick scooter': {'material_cost': '150',
                          'production_time': '9',
                          'weight_in_grams': '3200'},
        'VHS player': {'material_cost': '25',
                       'production_time': '4',
                       'weight_in_grams': '1200'},
        'Wall-mount diamond pickaxe': {'Count': 2,
                                       'material_cost': '15',
                                       'production_time': '1',
                                       'weight_in_grams': '695'},
        'Wireless headphones': {'Count': 2,
                                'material_cost': '89',
                                'production_time': '15',
                                'weight_in_grams': '540'},
        'World of Warcraft': {'material_cost': '119',
                              'production_time': '0.1',
                              'weight_in_grams': '300'},
        'Xbox Series X': {'Count': 2,
                          'material_cost': '399',
                          'production_time': '60',
                          'weight_in_grams': '4500'},
        'Zebra Jumpy': {'material_cost': '25',
                        'production_time': '1',
                        'weight_in_grams': '1337'}}
    assert pas.get_product_list() == product_list

    recipient_list = {
        'Alexis': {'Running shoes': {'Count': 2,
                                     'material_cost': '39',
                                     'production_time': '6',
                                     'weight_in_grams': '590'}},
        'Alvin': {'Swimming flippers': {'material_cost': '25',
                                        'production_time': '3',
                                        'weight_in_grams': '1000'}},
        'Amelia': {'Magic': {'Count': 4,
                             'material_cost': '189',
                             'production_time': '15',
                             'weight_in_grams': '900'},
                   'Wall-mount diamond pickaxe': {'Count': 2,
                                                  'material_cost': '15',
                                                  'production_time': '1',
                                                  'weight_in_grams': '695'}},
        'Ariel': {'Baby brother': {'material_cost': '4000',
                                   'production_time': '6480',
                                   'weight_in_grams': '3425'},
                  'Basketball': {'material_cost': '30',
                                 'production_time': '3',
                                 'weight_in_grams': '900'},
                  'LOL Dolls surprise egg': {'material_cost': '15',
                                             'production_time': '1',
                                             'weight_in_grams': '100'}},
        'Armando': {'Nerf rifle': {'material_cost': '30',
                                   'production_time': '10',
                                   'weight_in_grams': '300'},
                    'Remote controlled car': {'Count': 2,
                                              'material_cost': '37',
                                              'production_time': '13',
                                              'weight_in_grams': '2100'}},
        'Ash': {'Briefcase of art supplies': {'material_cost': '35',
                                              'production_time': '4',
                                              'weight_in_grams': '3200'}},
        'Aubrey': {'Toy dinosaur play set': {'material_cost': '15',
                                             'production_time': '2',
                                             'weight_in_grams': '150'}},
        'Baylee': {'Carbon fiber road bike': {'material_cost': '5499',
                                              'production_time': '100',
                                              'weight_in_grams': '6900'}},
        'Ben': {'Polar bear plushie': {'material_cost': '15',
                                       'production_time': '2',
                                       'weight_in_grams': '200'}},
        'Brennan': {'Pink tricycle': {'material_cost': '159',
                                      'production_time': '8',
                                      'weight_in_grams': '5400'}},
        'Caden': {'Baby born doll': {'material_cost': '25',
                                     'production_time': '3',
                                     'weight_in_grams': '900'},
                  'Car carpet': {'material_cost': '99',
                                 'production_time': '7',
                                 'weight_in_grams': '1500'},
                  'New phone': {'Count': 3,
                                'material_cost': '100',
                                'production_time': '9',
                                'weight_in_grams': '200'}},
        'Cain': {"Harry Potter and the Philosopher's Stone": {'material_cost': '7.99',
                                                              'production_time': '15',
                                                              'weight_in_grams': '300'},
                 'VHS player': {'material_cost': '25',
                                'production_time': '4',
                                'weight_in_grams': '1200'}},
        'Carissa': {'Baby Yoda plushie': {'material_cost': '29',
                                          'production_time': '3',
                                          'weight_in_grams': '200'},
                    'Football shoes': {'Count': 3,
                                       'material_cost': '59',
                                       'production_time': '7',
                                       'weight_in_grams': '690'},
                    'Nintendo Switch': {'material_cost': '359',
                                        'production_time': '19',
                                        'weight_in_grams': '200'}},
        'Chloe': {'Wireless headphones': {'material_cost': '89',
                                          'production_time': '15',
                                          'weight_in_grams': '540'}},
        'Darius': {'Baby born doll': {'Count': 3,
                                      'material_cost': '25',
                                      'production_time': '3',
                                      'weight_in_grams': '900'},
                   'Horse riding helmet': {'material_cost': '89',
                                           'production_time': '5',
                                           'weight_in_grams': '2500'},
                   'Magic': {'material_cost': '189',
                             'production_time': '15',
                             'weight_in_grams': '900'}},
        'Dylan': {'Cyberpunk 2077': {'material_cost': '59',
                                     'production_time': '0.5',
                                     'weight_in_grams': '30'},
                  'Roller skates': {'material_cost': '64',
                                    'production_time': '12',
                                    'weight_in_grams': '1670'}},
        'Edward': {'Baby born doll': {'material_cost': '25',
                                      'production_time': '3',
                                      'weight_in_grams': '900'},
                   'Tablet computer': {'Count': 2,
                                       'material_cost': '259',
                                       'production_time': '19',
                                       'weight_in_grams': '430'},
                   'Trick scooter': {'material_cost': '150',
                                     'production_time': '9',
                                     'weight_in_grams': '3200'}},
        'Eleanor': {'Polyhedral dice set': {'Count': 2,
                                            'material_cost': '13',
                                            'production_time': '3',
                                            'weight_in_grams': '10'},
                    'Spiderman costume': {'material_cost': '17',
                                          'production_time': '4',
                                          'weight_in_grams': '278'}},
        'Evelyn': {'7200 Riot Points gift card': {'material_cost': '50',
                                                  'production_time': '0.1',
                                                  'weight_in_grams': '10'},
                   'Avocado': {'material_cost': '2',
                               'production_time': '60',
                               'weight_in_grams': '68'},
                   'Wall-mount diamond pickaxe': {'material_cost': '15',
                                                  'production_time': '1',
                                                  'weight_in_grams': '695'}},
        'Freddie': {'Brunette Barbie doll': {'material_cost': '25',
                                             'production_time': '5',
                                             'weight_in_grams': '50'},
                    'Color pencil set': {'Count': 2,
                                         'material_cost': '6',
                                         'production_time': '1',
                                         'weight_in_grams': '100'},
                    'Toy train set': {'Count': 3,
                                      'material_cost': '49',
                                      'production_time': '6',
                                      'weight_in_grams': '890'}},
        'Harper': {'Jaipur board game': {'material_cost': '15',
                                         'production_time': '3',
                                         'weight_in_grams': '500'},
                   'Princess dress': {'material_cost': '17',
                                      'production_time': '5',
                                      'weight_in_grams': '278'},
                   'Toy kitchen set': {'material_cost': '89',
                                       'production_time': '10',
                                       'weight_in_grams': '2499'}},
        'Hollie': {'Acrylic paint brush set': {'material_cost': '13.59',
                                               'production_time': '3.4',
                                               'weight_in_grams': '200'},
                   'Football shoes': {'material_cost': '59',
                                      'production_time': '7',
                                      'weight_in_grams': '690'},
                   'Xbox Series X': {'material_cost': '399',
                                     'production_time': '60',
                                     'weight_in_grams': '4500'}},
        'Jaden': {'Dungeons and Dragons 5th Edition Starter Set': {'material_cost': '19.99',
                                                                   'production_time': '3',
                                                                   'weight_in_grams': '1000'},
                  'New phone': {'material_cost': '100',
                                'production_time': '9',
                                'weight_in_grams': '200'},
                  'Ninja Turtles backpack': {'Count': 2,
                                             'material_cost': '25',
                                             'production_time': '3',
                                             'weight_in_grams': '350'}},
        'Jakob': {'Frozen Elsa electric toothbrush': {'material_cost': '59',
                                                      'production_time': '4',
                                                      'weight_in_grams': '450'},
                  'Raspberry Pi 4': {'Count': 4,
                                     'material_cost': '57',
                                     'production_time': '10',
                                     'weight_in_grams': '100'}},
        'Jenson': {'Acrylic paint brush set': {'Count': 2,
                                               'material_cost': '13.59',
                                               'production_time': '3.4',
                                               'weight_in_grams': '200'},
                   'Jaipur board game': {'Count': 2,
                                         'material_cost': '15',
                                         'production_time': '3',
                                         'weight_in_grams': '500'},
                   'Toy train set': {'material_cost': '49',
                                     'production_time': '6',
                                     'weight_in_grams': '890'}},
        'Jess': {'Carbon fiber road bike': {'Count': 2,
                                            'material_cost': '5499',
                                            'production_time': '100',
                                            'weight_in_grams': '6900'}},
        'Jodie': {'7200 Riot Points gift card': {'material_cost': '50',
                                                 'production_time': '0.1',
                                                 'weight_in_grams': '10'},
                  'LED light up sneakers': {'material_cost': '35',
                                            'production_time': '5.89',
                                            'weight_in_grams': '250'},
                  'Small watering can': {'material_cost': '7',
                                         'production_time': '2',
                                         'weight_in_grams': '540'}},
        'Jordan': {'Magic': {'material_cost': '189',
                             'production_time': '15',
                             'weight_in_grams': '900'}},
        'Kai': {'Small watering can': {'material_cost': '7',
                                       'production_time': '2',
                                       'weight_in_grams': '540'}},
        'Keira': {'7200 Riot Points gift card': {'Count': 3,
                                                 'material_cost': '50',
                                                 'production_time': '0.1',
                                                 'weight_in_grams': '10'},
                  'LED light up sneakers': {'Count': 3,
                                            'material_cost': '35',
                                            'production_time': '5.89',
                                            'weight_in_grams': '250'}},
        'Kimberly': {'Raspberry Pi 4': {'material_cost': '57',
                                        'production_time': '10',
                                        'weight_in_grams': '100'},
                     'Wireless headphones': {'Count': 2,
                                             'material_cost': '89',
                                             'production_time': '15',
                                             'weight_in_grams': '540'}},
        'Lance': {'Indoor bowling set': {'material_cost': '69',
                                         'production_time': '6',
                                         'weight_in_grams': '3500'}},
        'Lesley': {'Briefcase of art supplies': {'Count': 2,
                                                 'material_cost': '35',
                                                 'production_time': '4',
                                                 'weight_in_grams': '3200'}},
        'Lexie': {'Mermaid barbie': {'material_cost': '25',
                                     'production_time': '5',
                                     'weight_in_grams': '50'},
                  'Pink fluffy pen': {'material_cost': '3',
                                      'production_time': '1',
                                      'weight_in_grams': '60'},
                  'World of Warcraft': {'material_cost': '119',
                                        'production_time': '0.1',
                                        'weight_in_grams': '300'}},
        'Libby': {'Lego death star': {'material_cost': '599',
                                      'production_time': '30',
                                      'weight_in_grams': '2000'},
                  'Princess dress': {'Count': 2,
                                     'material_cost': '17',
                                     'production_time': '5',
                                     'weight_in_grams': '278'},
                  'Zebra Jumpy': {'material_cost': '25',
                                  'production_time': '1',
                                  'weight_in_grams': '1337'}},
        'Lorelei': {'Digital camera': {'material_cost': '39',
                                       'production_time': '18',
                                       'weight_in_grams': '870'},
                    'Raspberry Pi 4': {'material_cost': '57',
                                       'production_time': '10',
                                       'weight_in_grams': '100'}},
        'Louis': {'Football shoes': {'material_cost': '59',
                                     'production_time': '7',
                                     'weight_in_grams': '690'},
                  'Tablet computer': {'material_cost': '259',
                                      'production_time': '19',
                                      'weight_in_grams': '430'}},
        'Marisol': {'Magic': {'material_cost': '189',
                              'production_time': '15',
                              'weight_in_grams': '900'}},
        'Mason': {'Beyblade Burst spinner': {'material_cost': '29.99',
                                             'production_time': '3',
                                             'weight_in_grams': '300'},
                  'Toy truck': {'material_cost': '13',
                                'production_time': '4',
                                'weight_in_grams': '300'}},
        'Peter': {'LED light up sneakers': {'material_cost': '35',
                                            'production_time': '5.89',
                                            'weight_in_grams': '250'}},
        'Phoebe': {'Clear Night Sky puzzle': {'material_cost': '45',
                                              'production_time': '50',
                                              'weight_in_grams': '1500'},
                   'Toy train set': {'material_cost': '49',
                                     'production_time': '6',
                                     'weight_in_grams': '890'}},
        'Quinn': {'Small watering can': {'Count': 3,
                                         'material_cost': '7',
                                         'production_time': '2',
                                         'weight_in_grams': '540'}},
        'Rachael': {'Clear Night Sky puzzle': {'Count': 2,
                                               'material_cost': '45',
                                               'production_time': '50',
                                               'weight_in_grams': '1500'},
                    'Doll stroller': {'material_cost': '56',
                                      'production_time': '15',
                                      'weight_in_grams': '2100'},
                    'Xbox Series X': {'Count': 2,
                                      'material_cost': '399',
                                      'production_time': '60',
                                      'weight_in_grams': '4500'}},
        'Reid': {'Book about dinosaurs': {'material_cost': '5',
                                          'production_time': '8',
                                          'weight_in_grams': '250'},
                 'Color pencil set': {'material_cost': '6',
                                      'production_time': '1',
                                      'weight_in_grams': '100'},
                 'Skateboard': {'material_cost': '67',
                                'production_time': '9',
                                'weight_in_grams': '1350'}},
        'Rhys': {'Crayons': {'material_cost': '5',
                             'production_time': '1',
                             'weight_in_grams': '50'}},
        'Scarlett': {'Ballet shoes': {'material_cost': '39',
                                      'production_time': '2',
                                      'weight_in_grams': '150'},
                     'Piggy bank': {'material_cost': '13',
                                    'production_time': '4',
                                    'weight_in_grams': '300'},
                     'Running shoes': {'material_cost': '39',
                                       'production_time': '6',
                                       'weight_in_grams': '590'}},
        'Scott': {'Polyhedral dice set': {'material_cost': '13',
                                          'production_time': '3',
                                          'weight_in_grams': '10'}},
        'Skyler': {'New phone': {'material_cost': '100',
                                 'production_time': '9',
                                 'weight_in_grams': '200'}},
        'Sofie': {'Ninja Turtles backpack': {'material_cost': '25',
                                             'production_time': '3',
                                             'weight_in_grams': '350'}},
        'Spencer': {'Fortnite t-shirt': {'material_cost': '5',
                                         'production_time': '1',
                                         'weight_in_grams': '100'},
                    'Raspberry Pi 4': {'material_cost': '57',
                                       'production_time': '10',
                                       'weight_in_grams': '100'},
                    'Remote controlled car': {'material_cost': '37',
                                              'production_time': '13',
                                              'weight_in_grams': '2100'}}}
    assert pas.get_recipient_list() == recipient_list

    product_info = pas.get_product_info(
        "Acrylic paint brush set")
    assert product_info == '{"gift":"Acrylic paint brush set","material_cost":13.59' \
                           ',"production_time":3.4,"weight_in_grams":200}'
    assert pas.parse_product_info(product_info) == ['Acrylic paint brush set',
                                                    {'material_cost': '13.59', 'production_time': '3.4',
                                                     'weight_in_grams': '200'}]

    pas.add_parsed_product_info(pas.parse_product_info(product_info))
    assert pas.products['Acrylic paint brush set'] == {'material_cost': '13.59', 'production_time': '3.4',
                                                       'weight_in_grams': '200'}
